# -*- coding: utf-8 -*-
"""Data_Manipulation_Sangeetha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xAKSgfLWow0PfGhKCxItHWDVoEcSi7lB

Load the dataset with Pandas
1. Mount the google drive and authenticate to access the dataset from google drive to google colab
2. Import the dataset to colab using Pandas
"""

from google.colab import drive
drive.mount('/content/drive')

"""Display the data
1. View the dataset details with Pandas
2. use head() to view the first few records
"""

import pandas as pd
file_path = '/content/drive/MyDrive/retail_sales_dataset.csv'
df = pd.read_csv(file_path)
df.head()

"""Filtering

Filter the products belonging to Region "West"

"""

region_west = df[df['Region'] == 'West']
region_west.head()

"""Adding a column named 'Revenue'
1. Create a column Revenue which is the product of Quantity and Unit price
2. View the dataframe post column addition
"""

revenue = df['Quantity'] * df['Unit_Price']
df['Revenue'] = revenue
df

"""Sorting the data

Sort the dataframe by Revenue of the products
"""

df.sort_values(by = 'Revenue', ascending = False)

"""Handling Missing values (if any):

1. Verify if there are any missing values in the dataset
2. Display the count of null values per column
"""

sample = df.copy()
print("To check if there are any missing values per column:")
print(sample.isna().sum())