# -*- coding: utf-8 -*-
"""Statistical_Analysis_Sangeetha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A2nWD6rBZOl7INQJX7_mT0OjuHLaZJLR

Descriptive Statistics

1. Calculation of mean, variance and SD using statsmodels
2. Identifying the Standard error of the mean

1. Import the dataset to perform the calculations
2. Import all the necessary Python libraries to perform the statmodels
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import seaborn as sns
import numpy as np

import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.stats.weightstats import ttest_ind
from statsmodels.stats.anova import anova_lm

import matplotlib.pyplot as plt
file_path = '/content/drive/MyDrive/retail_sales_dataset.csv'
df = pd.read_csv(file_path)
df.head()

"""Adding a column named 'Revenue'

Create a column Revenue which is the product of Quantity and Unit price
View the dataframe post column addition
"""

revenue = df['Quantity'] * df['Unit_Price']
df['Revenue'] = revenue
df

"""Unweighted Descriptive stats for Unit Price in the given dataset"""

from statsmodels.stats.weightstats import DescrStatsW

# Unweighted descriptive stats for Unit Price
d = DescrStatsW(df['Unit_Price'])
summary = {
    "mean": d.mean,
    "std": d.std,
    "var": d.var,
    "std_err_mean": d.std_mean,  # standard error of the mean
    "nobs": d.nobs
}
summary

"""Weighted statistics using Numpy with sample array values"""

from statsmodels.stats.weightstats import DescrStatsW
import numpy as np

# weighted statistics for Product category id and Unit Price
price = np.array([800, 790, 1000])
pdt_category = np.array([5, 2, 1])  # Home=5, Fashion=2, Beauty=1

unweighted = DescrStatsW(price)
weighted = DescrStatsW(price, weights=pdt_category)

print("Unweighted mean:", unweighted.mean)
print("Weighted mean:", weighted.mean)

"""Correlation

Inspecting linear relationships among the various columns of the dataset:
1.Quantity
2.Unit Price
3.Revenue
"""

df[["Quantity","Unit_Price","Revenue"]].corr()

"""Hypothesis Testing - Two sample t test

Is the average revenue of Electronics is different from that of the Fashion products?

Hypothesis:
Null hypothesis (H₀):
The two product categories generate the same mean Revenue

Alternative hypothesis (H₁):
The two product categories generate the different mean Revenue
"""

file_path = '/content/drive/MyDrive/retail_sales_dataset.csv'
df = pd.read_csv(file_path)
df.head()

revenue = df['Quantity'] * df['Unit_Price']
df['Revenue'] = revenue
df

electronics = df.loc[df["Product_Category"] == "Electronics", "Revenue"]
fashion = df.loc[df["Product_Category"] == "Fashion", "Revenue"]

tstat, pval, degrees_freedom = ttest_ind(electronics, fashion, usevar="pooled")  # equal variances assumed
{"t_statistic": float(tstat), "p_value": float(pval), "degrees_freedom": float(degrees_freedom)}

"""Simple Linear Regression

Objective : To predict Order_Revenue (Y) based on Quantity (X) using Ordinary Least Squares (OLS).

"""

Y = df["Revenue"]
X = df["Quantity"]

X = sm.add_constant(X)
model = sm.OLS(Y, X).fit()
model.summary()

"""Visualizing the fit

"""

plt.scatter(df["Quantity"], df["Revenue"], alpha=0.7)
x_line = np.linspace(df["Quantity"].min(), df["Revenue"].max(), 100)
X_line = sm.add_constant(x_line)
y_hat = model.predict(X_line)
plt.plot(x_line, y_hat)
plt.xlabel("Quantity")
plt.ylabel("Revenue")
plt.title("OLS: Revenue ~ Quantity")
plt.show()

"""Multiple Linear Regression (OLS with 2 predictors)

Extend the model to include two predictors: Quantity and Unit_Price
"""

y = df["Revenue"]
X = df[["Quantity", "Unit_Price"]]
X = sm.add_constant(X)

ols_multi = sm.OLS(y, X).fit()
ols_multi.summary()